### ISSUE TITLE
Small question, not an issue

### ISSUE THREAD

**Issue by bentcoder** [ajouve/time-api#1]
Hi @ajouve ,

First of all, it is a very helpful and clean example so that you for it. I just want to find out why you didn't create and use **your own** `refresh_token_class` and `auth_code_class` classes in `app/config/config.yml` file? I'm just trying to understand how OAuth in Symfony works. After going through other examples and the documentations, I got a bit confused.

Not: I haven't implemented your example however I'll do it soon and I might come back and ask you question if I have any, If you don't mind.

Thanks

**Comment by ajouve** [comment]
Hi @BentCoder,

Thanks for your message.

I didn't create my own `RefreshToken` and `AuthCode` class because it was not needed in the example.
But if you want to use it, you will need to implement those classes.

The `refresh_token` is used to create a new `access_token` without sending yours credentials to the API. You can get a new access token via `/oauth/v2/token?refresh_token={YOUR_REFRESH_TOKEN}`

The `auth_code` will allow third party provider to login via your API, like Google or Facebook login

Hope it will help :)

**Comment by bentcoder** [comment]
Hi @ajouve ,

Thanks for the answer. I implemented your example but getting error below while trying to generate the token.

```
{
    "error": "invalid_client",
    "error_description": "The client credentials are invalid"
}
```

**HOW I TEST**

**Create client**
I checked the database and can confirm that the record exists in Client table as shown below.

```
Mac:oauth-server bentcoder$ app/console create:oauth:client --grant-type="client_credentials"
OAuth client has been created...
Public ID: 7_15cekk751d40osk884w0so40wskw8w00g0w4o48sg4ssoswc8s
Secret ID: 2tbei9s7t6o00k8s800ss4g44ksg0gwcgs84kco4swkwwkcoo8
```

**Get token**
Unfortunately this is the one which causes error above.

```
http://oauth-server.local/app_dev.php/oauth/v2/token?client_id=7_15cekk751d40osk884w0so40wskw8w00g0w4o48sg4ssoswc8s&client_secret=2tbei9s7t6o00k8s800ss4g44ksg0gwcgs84kco4swkwwkcoo8&grant_type=client_credentials
```

Thanks

**Comment by bentcoder** [comment]
I see... When I send a GET request to that URI with Chrome Postman extension, error occurs because I forgot to clean headers. If I try to access the same URI, it works as expected and I get the token.

So It was all my mistake. Anyway, I'll move on to client app now.

**Comment by ajouve** [comment]
Cool, ask if you have others questions

**Comment by bentcoder** [comment]
Hi @ajouve ,

Everything works fine so far. One last question, I just want to understand [how and where](https://github.com/ajouve/time-reader/blob/master/src/AppBundle/Controller/DefaultController.php#L59) exactly are you preventing calls to `oauth/v2/token`. As far as I can see, both lines below don't prevent it because you're calling them in each requests.

```
$token = new ClientCredentials($oauth2Client, $config);
$oauth2 = new Oauth2Subscriber($token);
```

When I echo `$subscriber->getAccessToken()->getToken()` it is always the same however when I echo `$token->getToken()->getToken()` it is always different. It is a bit confusing to me.

Thanks

**Comment by ajouve** [comment]
When you add a subscriber to it will do a check on each request using the client.

```
$client = new Client([
      'defaults' => [
          'auth' => 'oauth2',
          'subscribers' => [$oauth2],
      ],
  ]);
```

In this case the OAuth will be reload on each request, unless you cache the token `http://blog.ajouve.com/symfony2/oauth2/microservice/2015/12/19/oauth-microservice-symfony.html#improvements`

**Comment by bentcoder** [comment]
`$token = new ClientCredentials($oauth2Client, $config);` would always hit server because caching is done after that line so hence reason `$token->getToken()->getToken()` returns different token. I think `$token = new ClientCredentials($oauth2Client, $config);` should never be called if the token is in cache.

**Comment by ajouve** [comment]
The new token is generated calling `$token->getToken()->getToken()` not creating the object with `$token = new ClientCredentials($oauth2Client, $config);` have a look to `commerceguys/guzzle-oauth2-plugin/src/GrantType/GrantTypeBase.php` line 89.
